version: '3.8'

services:
  vehicle-api:
    image: vehicle-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/vehicle_mgt
    ports:
      - "3000:3000"
    depends_on:
      - vehicle-db

  vehicle-db:
    image: postgres
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vehicle-pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "15432:80"
    depends_on:
      - vehicle-db

volumes:
  postgres:
